-- MySQL Script generated by MySQL Workbench
-- Thu Jun 30 02:57:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alkemy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `alkemy` ;

-- -----------------------------------------------------
-- Schema alkemy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alkemy` DEFAULT CHARACTER SET utf8 ;
USE `alkemy` ;

-- -----------------------------------------------------
-- Table `alkemy`.`typeOperations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alkemy`.`typeOperations` ;

CREATE TABLE IF NOT EXISTS `alkemy`.`typeOperations` (
  `idTypeOperation` INT NOT NULL AUTO_INCREMENT,
  `nameTypeOperation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTypeOperation`),
  UNIQUE INDEX `idTypeOperations_UNIQUE` (`idTypeOperation` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alkemy`.`operations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alkemy`.`operations` ;

CREATE TABLE IF NOT EXISTS `alkemy`.`operations` (
  `idOperations` INT NOT NULL AUTO_INCREMENT,
  `conceptOperation` VARCHAR(100) NOT NULL,
  `amountOperation` VARCHAR(256) NOT NULL,
  `dateOperation` VARCHAR(45) NOT NULL,
  `idTypeOperation` INT NOT NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`idOperations`, `idTypeOperation`),
  UNIQUE INDEX `idOperations_UNIQUE` (`idOperations` ASC) VISIBLE,
  INDEX `fk_operations_typeOperations_idx` (`idTypeOperation` ASC) VISIBLE,
  CONSTRAINT `fk_operations_typeOperations`
    FOREIGN KEY (`idTypeOperation`)
    REFERENCES `alkemy`.`typeOperations` (`idTypeOperation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
